import React, { ReactNode } from 'react'
import Navigation from '@/ui/domain/navigation/Navigation'
import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Good Next 14',
  description: 'Generated by Next.js',
}

interface RootLayoutProps {
  children: ReactNode
}

const RootLayout = ({ children }: RootLayoutProps) => {
  return (
    <html lang={'ko'}>
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  )
}

export default RootLayout
