import React, { ReactNode } from 'react'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

interface RootLayoutProps {
  children: ReactNode
}

const RootLayout = ({ children }: RootLayoutProps) => {
  return (
    <html lang={'ko'}>
      <body>{children}</body>
    </html>
  )
}

export default RootLayout
