import React from 'react'
import MovieDetail from '@/ui/domain/post/components/templates/MovieDetail'
import { Metadata } from 'next'
import MovieRepository from '@/repository/movies/MovieRepository'
import { redirect } from 'next/navigation'

export const metadata: Metadata = {
  title: 'Post',
  description: 'Generated by Next.js',
}

type PageParams = {
  movieId: string
}

type PageSearchParams = {}

interface Props extends NextPageProps<PageParams, PageSearchParams> {}

const Page = async ({ params, searchParams }: Props) => {
  if (!params?.movieId || isNaN(+params.movieId)) {
    return redirect('/400')
  }

  const movieResponse = await MovieRepository.findMovieById(+params.movieId)

  if (!movieResponse) {
    return redirect('/404')
  }

  return <MovieDetail movie={movieResponse} />
}

export default Page
