import React from 'react'
import PostDetail from '@/ui/domain/post/components/templates/PostDetail'
import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Post',
  description: 'Generated by Next.js',
}

type PageParams = {
  movieId: string
}

type PageSearchParams = {}

interface Props extends NextPageProps<PageParams, PageSearchParams> {}

const Page = ({ params, searchParams }: Props) => {
  return <PostDetail />
}

export default Page
