import React from 'react'
import PostDetail from '@/ui/domain/post/components/templates/PostDetail'
import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Post',
  description: 'Generated by Next.js',
}

interface Props {}

const Page = (props: Props) => {
  console.log(props)
  return <PostDetail />
}

export default Page
